FROM docker.io/rocker/r-ver:4.3.2 as build

RUN apt-get -y update && apt-get install -y \
      default-jre \
      default-jdk \
      libxml2-dev \
      libglpk-dev \
      libsodium-dev \
      libsecret-1-dev \
      libssl-dev  \
      --no-install-recommends \
      && apt-get clean

WORKDIR /project

COPY docker/setupTable1Env.R setupTable1Env.R
RUN R cmd javareconf &&  \
    Rscript setupTable1Env.R 

RUN Rscript -e "DatabaseConnector::downloadJdbcDrivers(dbms='all', pathToDriver='/database_drivers/')"

FROM docker.io/rocker/r-ver:4.3.2

COPY --from=build /project /project
COPY --from=build /database_drivers /database_drivers
COPY --from=build /usr/local/lib/R/site-library /usr/local/lib/R/site-library

RUN apt-get -y update && apt-get install -y \
      default-jre \
      libxml2 \
      libglpk40 \
      libssl3 \
      --no-install-recommends \
      && R cmd javareconf \
      && apt-get clean
      
RUN mkdir /output

WORKDIR /project

# copy
COPY cohorts cohorts
COPY codeToRunTable1.R codeToRunTable1.R
