install.packages("R6")
install.packages("dplyr")
install.packages("openssl")
install.packages("keyring")
install.packages("remotes")
install.packages("DatabaseConnector")
install.packages("ParallelLogger")
remotes::install_github("ohdsi/Strategus@v0.1.0")
