install.packages("R6")
install.packages("dplyr")
install.packages("openssl")
install.packages("remotes")
install.packages("DatabaseConnector")
install.packages("ParallelLogger")
install.packages("keyring")
remotes::install_github("mi-erasmusmc/Strategus@v0.1.2")
